name: Build macOS + Android (NO MORE ERRORS)

on:
  workflow_dispatch:

jobs:
  build-mac-android:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: stable

      - name: Fix intl version conflict
        run: |
          cd simple_live_app
          sed -i '' 's/intl: ^0.20.2/intl: 0.19.0/g' pubspec.yaml

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build Android APK
        run: |
          cd simple_live_app
          flutter build apk --release

      - name: Upload Android
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: simple_live_app/build/app/outputs/flutter-apk/app-release.apk

      - name: Build macOS
        run: |
          cd simple_live_app
          flutter build macos --release

      - name: Upload macOS
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: simple_live_app/build/macos/Build/Products/Release
